---
title: "CensusBurbank"
author: "Christian Leonard"
date: "9/9/2021"
output: html_document
---


```{r libraries echo=F}
library(dplyr)
library(tigris)
library(tidyverse)
library(ggplot2)
library(sf)
library(sp)
library(scales)
library(censusapi)
library(viridis)
library(leaflet)
library(ggtext)
library(rgdal)
```

# Import data (code from Census Bureau)

```{r specify paths}
header_file_path <- "Data/cageo2020.pl"
part1_file_path  <- "Data/ca000012020.pl"
part2_file_path  <- "Data/ca000022020.pl"
part3_file_path  <- "Data/ca000032020.pl"
```

```{r import census data}
header <- read.delim(header_file_path, header=FALSE, colClasses="character", sep="|")
part1  <- read.delim(part1_file_path,  header=FALSE, colClasses="character", sep="|")
part2  <- read.delim(part2_file_path,  header=FALSE, colClasses="character", sep="|")
part3  <- read.delim(part3_file_path,  header=FALSE, colClasses="character", sep="|")
```

```{r colnames}

colnames(header) <- c("FILEID", "STUSAB", "SUMLEV", "GEOVAR", "GEOCOMP", "CHARITER", "CIFSN", "LOGRECNO", "GEOID","GEOCODE", "REGION", "DIVISION", "STATE", "STATENS", "COUNTY", "COUNTYCC", "COUNTYNS", "COUSUB", "COUSUBCC", "COUSUBNS", "SUBMCD", "SUBMCDCC", "SUBMCDNS", "ESTATE", "ESTATECC", "ESTATENS", "CONCIT", "CONCITCC", "CONCITNS", "PLACE", "PLACECC", "PLACENS", "TRACT", "BLKGRP", "BLOCK", "AIANHH", "AIHHTLI", "AIANHHFP", "AIANHHCC", "AIANHHNS", "AITS", "AITSFP", "AITSCC", "AITSNS", "TTRACT", "TBLKGRP", "ANRC", "ANRCCC", "ANRCNS", "CBSA", "MEMI", "CSA", "METDIV", "NECTA", "NMEMI", "CNECTA", "NECTADIV", "CBSAPCI", "NECTAPCI", "UA", "UATYPE", "UR", "CD116", "CD118", "CD119", "CD120", "CD121", "SLDU18", "SLDU22", "SLDU24", "SLDU26", "SLDU28", "SLDL18", "SLDL22", "SLDL24", "SLDL26", "SLDL28", "VTD", "VTDI", "ZCTA", "SDELM", "SDSEC", "SDUNI", "PUMA", "AREALAND", "AREAWATR", "BASENAME", "NAME", "FUNCSTAT", "GCUNI", "POP100", "HU100", "INTPTLAT", "INTPTLON", "LSADC", "PARTFLAG", "UGA")
colnames(part1) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO", 
                     paste0("P00", c(10001:10071, 20001:20073)))
colnames(part2) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO", 
                     paste0("P00", c(30001:30071, 40001:40073)), 
                     paste0("H00", 10001:10003))
colnames(part3) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO",
                     paste0("P00", 50001:50010))
```

```{r merge and order}

combine <- Reduce(function(x,y) {merge(x, y, by=c("LOGRECNO", "STUSAB", "FILEID", "CHARITER"))}, list(header[,-7], part1[,-4], part2[,-4], part3))
combine <- combine[order(combine$LOGRECNO), c("FILEID", "STUSAB", "SUMLEV", "GEOVAR", "GEOCOMP", "CHARITER", "CIFSN", "LOGRECNO", "GEOID", "GEOCODE", "REGION", "DIVISION", "STATE", "STATENS", "COUNTY", "COUNTYCC", "COUNTYNS", "COUSUB", "COUSUBCC", "COUSUBNS", "SUBMCD", "SUBMCDCC", "SUBMCDNS", "ESTATE", "ESTATECC", "ESTATENS", "CONCIT", "CONCITCC", "CONCITNS", "PLACE", "PLACECC", "PLACENS", "TRACT", "BLKGRP", "BLOCK", "AIANHH", "AIHHTLI", "AIANHHFP", "AIANHHCC", "AIANHHNS", "AITS", "AITSFP", "AITSCC", "AITSNS", "TTRACT", "TBLKGRP", "ANRC", "ANRCCC", "ANRCNS", "CBSA", "MEMI", "CSA", "METDIV", "NECTA", "NMEMI", "CNECTA", "NECTADIV", "CBSAPCI", "NECTAPCI", "UA", "UATYPE", "UR", "CD116", "CD118", "CD119", "CD120", "CD121", "SLDU18", "SLDU22", "SLDU24", "SLDU26", "SLDU28", "SLDL18", "SLDL22", "SLDL24", "SLDL26", "SLDL28", "VTD", "VTDI", "ZCTA", "SDELM", "SDSEC", "SDUNI", "PUMA", "AREALAND", "AREAWATR", "BASENAME", "NAME", "FUNCSTAT", "GCUNI", "POP100", "HU100", "INTPTLAT", "INTPTLON", "LSADC", "PARTFLAG", "UGA", paste0("P00", c(10001:10071, 20001:20073)), paste0("P00", c(30001:30071, 40001:40073)), paste0("H00", 10001:10003), paste0("P00", 50001:50010))]

rownames(combine) <- 1:nrow(combine)
```

# CA-specific stuff

```{r filter to CA}

CAtractsPop <- filter(combine, SUMLEV=="140")
```

```{r import CA shapefile}

# From https://www.census.gov/cgi-bin/geo/shapefiles/index.php
CAtractsLocation <- "Data/tl_2020_06_tract.shp"
CAtracts <- st_read(CAtractsLocation)
```

```{r join CA population/shapefile}

CAtractsFilled <- left_join(CAtractsPop, CAtracts, by=c("GEOCODE"="GEOID"))
```

# Burbank-specific stuff

```{r Burbank 2020 tracts}

BURTracts <- c(3101, 3102.01, 3102.02, 3103, 3104, 3105.01, 3106.01, 3106.02, 3107.01, 3107.02, 3107.03, 3107.04, 3107.05, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3116.01, 3116.02, 3117, 3118.01, 3118.02, 9800.01)

# Filters CA data to only tract-level Burbank data
BURtractsFilled <- filter(CAtractsFilled, BASENAME %in% BURTracts, CSA=="348")

# Keep desired cols
BURcols.num <- c("P0010001", "P0010009", "P0020002", "P0020005", "P0020006", "P0020008", "HU100")
BURtractsSelected2020 <- select(BURtractsFilled, BASENAME, all_of(BURcols.num), geometry)

# Convert pop cols to numeric
BURtractsSelected2020[BURcols.num] <- sapply(BURtractsSelected2020[BURcols.num], as.numeric)

## Rename cols
BURtractsSelected2020 <- BURtractsSelected2020 %>%
  rename(Total = P0010001, TwoMoreRacesAll = P0010009, Hispanic = P0020002, WhiteAlone = P0020005, BlackAlone = P0020006, AsianAlone = P0020008, HousingUnits = HU100)

```

# Add 2010 Burbank data

```{r Burbank 2010 pop data}

# Import (file contains LA County tracts with specified variables)
Census2010 <- read.csv("Data/LACcensus2010.csv")

# Filter to Burbank
Census2010$Name <- str_sub(Census2010$LSAD_NAME, 14, -1) # Fixes name for easier joining later
Census2010 <- select(Census2010, -LSAD_NAME, -tract, -county, -state)
BURtracts2010 <- filter(Census2010, Name %in% BURTracts) %>% 
  rename(Total = P001001, TwoMoreRacesAll = P001009, Hispanic = P002002, WhiteAlone = P002005, BlackAlone = P002006, AsianAlone = P002008, HousingUnits = H001001) # Renames cols

```

```{r Burbank 2010 shapefiles}

# Import 2010 shapefiles
CAtractsLocation2010 <- "Data/tl_2010_06037_tract10.shp"
CAtracts2010 <- st_read(CAtractsLocation2010)

```

```{r join 2010 pop data and SFs}

BURtracts2010_filled <- left_join(BURtracts2010, CAtracts2010, by=c("Name" = "NAME10"))

```

```{r combine 2020 SFs}

# The Bureau split up two of Burbank's tracts — 3107.02 (becoming 3107.04 and 3107.05) and 3116 (becoming 3116.01 and 3116.02) — between 2010 and 2020. We're going to recombine the new tracts for easier comparison between the releases.

BURtractsReformed2020 <- BURtractsSelected2020

BURtractsReformed2020 <- BURtractsReformed2020 %>% 
  mutate(BASENAME=str_replace(BASENAME, "3107.04", "3107.02"),
         BASENAME=str_replace(BASENAME, "3107.05", "3107.02"),
         BASENAME=str_replace(BASENAME, "3116.01", "3116"),
         BASENAME=str_replace(BASENAME, "3116.02", "3116")) %>% 
  select(-geometry)

BURtractsReformed2020 <- BURtractsReformed2020 %>% 
  group_by(BASENAME) %>% 
  summarize(Total=sum(Total),
            TwoMoreRacesAll = sum(TwoMoreRacesAll),
            Hispanic=sum(Hispanic),
            WhiteAlone = sum(WhiteAlone),
            BlackAlone = sum(BlackAlone),
            AsianAlone = sum(AsianAlone),
            HousingUnits = sum(HousingUnits))
```

```{r Combine decades}
# Joins 2010 with 2020 data

BURtractsReformedcombo <- left_join(BURtractsReformed2020, BURtracts2010_filled, by=c("BASENAME" = "Name"), suffix=c(".new", ".old"))

```

# Percentage changes

```{r flat difference}
# To identify which tracts had the greatest percentage population change from 2010 to 2020, we need to first figure out the numerical differences for each tract.

BURtractschanges <- BURtractsReformedcombo %>% 
  mutate(Total.change = Total.new-Total.old,
         TwoMoreRacesAll.change = TwoMoreRacesAll.new - TwoMoreRacesAll.old,
         Hispanic.change = Hispanic.new - Hispanic.old,
         WhiteAlone.change = WhiteAlone.new - WhiteAlone.old,
         BlackAlone.change = BlackAlone.new - BlackAlone.old,
         AsianAlone.change = AsianAlone.new - AsianAlone.old,
         HousingUnits.change = HousingUnits.new - HousingUnits.old)

```

```{r percentage difference}

BURtractsPC <- BURtractschanges %>% 
  mutate(Total.pct.change = round(Total.change/Total.old*100, digits=1),
         TwoMoreRaces.pct.change = round(TwoMoreRacesAll.change/TwoMoreRacesAll.old*100, digits=1),
         Hispanic.pct.change = round(Hispanic.change/Hispanic.old*100, digits=1),
         WhiteAlone.pct.change = round(WhiteAlone.change/WhiteAlone.old*100, digits=1),
         BlackAlone.pct.change = round(BlackAlone.change/BlackAlone.old*100, digits=1),
         AsianAlone.pct.change = round(AsianAlone.change/AsianAlone.old*100, digits=1),
         HousingUnits.pct.change = round(HousingUnits.change/HousingUnits.old*100, digits=1))

```

# Visualization

```{r leaflet setup}
# Removes airport tract (no reliable population data, and the N/A messes up the Leaflet)
leaflet_data <- BURtractsPC
leaflet_data <- leaflet_data[-c(24),]

# Palette
pal <- colorNumeric("Blues", domain=leaflet_data$Total.pct.change)

# Pop-up text
popup <- paste0("<b>Pop. Increase: </b>", as.character(leaflet_data$Total.pct.change), "%", "<br/>", "2010 Population: ", as.character(leaflet_data$Total.old), "<br/>", "2020 Population: ", as.character(leaflet_data$Total.new), "<br/>", "<b>Housing Unit Increase: </b>", as.character(leaflet_data$HousingUnits.pct.change), "%", "<br/>", "2010 Housing Unit Count: ", as.character(leaflet_data$HousingUnits.old), "<br/>", "2020 Housing Unit Count: ", as.character(leaflet_data$HousingUnits.new))
```

```{r leaflet run}

leaflet() %>% 
  addTiles() %>%
  setView(-118.32215002962275, 34.187441982489034, zoom=13) %>% 
  addPolygons(data=leaflet_data$geometry,
              fillColor=pal(leaflet_data$Total.pct.change),
              fillOpacity=0.7,
              weight=3,
              smoothFactor=0.2,
              popup=popup,
              highlight=highlightOptions(
                weight=6,
                color="#837F7F",
                fillOpacity=0.8,
                bringToFront=T)) %>% 
  addLegend(pal=pal,
            values=leaflet_data$Total.pct.change,
            position="bottomright",
            title="Population Change",
            labFormat=labelFormat(suffix="%"))
```
